apiVersion: v1
kind: Pod
metadata:
  name: gpu-test
  annotations:
    container.apparmor.security.beta.kubernetes.io/cuda-container: unconfined
spec:
  runtimeClassName: nvidia
  containers:
    - name: cuda-container
      image: nvidia/cuda:12.2.0-base-ubuntu22.04
      command: ["sleep", "infinity"]
      resources:
        limits:
          nvidia.com/gpu: 1
  restartPolicy: Never
