apiVersion: v1
kind: ConfigMap
metadata:
  name: karakeep-config
  namespace: bookmarks
data:
  # Required by KaraKeep (NextAuth needs the public URL)
  NEXTAUTH_URL: "https://bookmarks.publio.online"
  # KaraKeep stores its SQLite DB and (by default) assets under DATA_DIR
  DATA_DIR: "/data"
  # Point KaraKeep to the meilisearch service (enables search)
  MEILI_ADDR: "http://meilisearch:7700"
  # Recommended by docs for SQLite perf unless on network storage
  DB_WAL_MODE: "true"
  # Optional: enable OpenAI tagging (uncomment when you add the secret)
  INFERENCE_TEXT_MODEL: "gpt-5-mini"
  INFERENCE_IMAGE_MODEL: "gpt-5-mini"
