apiVersion: v1
kind: Service
metadata:
  name: immich-postgresql
  namespace: immich
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    cnpg.io/cluster: immich-db
  type: ClusterIP
