apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: umami-db
  namespace: umami
spec:
  instances: 1
  storage:
    size: 10Gi
  bootstrap:
    initdb:
      database: umami
      owner: umami
  enableSuperuserAccess: false
  monitoring:
    enablePodMonitor: true
  resources:
    requests:
      memory: "256Mi"
      cpu: "250m"
    limits:
      memory: "512Mi"
      cpu: "500m"

