apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: immich-postgresql
  namespace: immich
spec:
  serviceName: immich-postgresql
  replicas: 1
  selector:
    matchLabels:
      app: immich-postgresql
  template:
    metadata:
      labels:
        app: immich-postgresql
    spec:
      containers:
        - name: postgres
          image: ghcr.io/immich-app/postgres:16-vectorchord0.3.0-pgvectors0.3.0  # pick the tag matching your Immich release
          env:
            - name: POSTGRES_DB
              value: immich
            - name: POSTGRES_USER
              value: immich
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: immich-postgres-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_INITDB_ARGS
              value: "--data-checksums"
            # If your data is not on SSD, uncomment:
            # - name: DB_STORAGE_TYPE
            #   value: "HDD"
          ports:
            - containerPort: 5432
              name: postgres
          readinessProbe:
            exec:
              command: ["sh", "-c", "pg_isready -U immich -d immich"]
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            exec:
              command: ["sh", "-c", "pg_isready -U immich"]
            initialDelaySeconds: 30
            periodSeconds: 10
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: ssd-hostpath-immich
        resources:
          requests:
            storage: 20Gi
