apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ingress-reader-binding
  namespace: heimat
subjects:
- kind: ServiceAccount
  name: ingress-reader
  namespace: heimat
roleRef:
  kind: Role
  name: ingress-reader-role
  apiGroup: rbac.authorization.k8s.io

