apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: heimat
  name: ingress-reader-role
rules:
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get", "list"]

