apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-media-pv
  labels:
    type: local
spec:
  storageClassName: jellyfin-hostpath
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/zweiterra/jellyfin-media"
