apiVersion: v1
kind: ConfigMap
metadata:
  name: asterisk-config
  namespace: phone
data:
  sip.conf: |
    [general]
    context=default
    bindport=5060
    bindaddr=0.0.0.0
    allowguest=no
    allow=ulaw
    alwaysauthreject=yes
    canreinvite=no

    [homephone]
    type=friend
    username=homephone
    secret=1234
    host=dynamic
    context=default
    nat=yes

    [myphone]
    type=friend
    username=myphone
    secret=1312
    host=dynamic
    context=default
    nat=yes

    [wifephone]
    type=friend
    username=wifephone
    secret=8765
    host=dynamic
    context=default
    nat=yes

    [wurmac]
    type=friend
    username=wurmac
    secret=1312
    host=dynamic
    context=default
    nat=yes

    [lumac]
    type=friend
    username=lumac
    secret=1312
    host=dynamic
    context=default
    nat=yes


  extensions.conf: |
    [default]
    exten => 1000,1,Dial(SIP/homephone)
    exten => 1001,1,Dial(SIP/myphone)
    exten => 1002,1,Dial(SIP/wifephone)
    exten => 1003,1,Dial(SIP/wurmac)
    exten => 1004,1,Dial(SIP/lumac)

  modules.conf: |
    [modules]
    autoload=yes
