apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-config
  namespace: jellyfin
spec:
  accessModes: [ "ReadWriteOnce" ]
  resources: { requests: { storage: 10Gi } }
  storageClassName: microk8s-hostpath
  volumeName: pv-jellyfin-config
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-transcode
  namespace: jellyfin
spec:
  accessModes: [ "ReadWriteOnce" ]
  resources: { requests: { storage: 20Gi } }
  storageClassName: microk8s-hostpath
  volumeName: pv-jellyfin-transcode
