---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-transcode-pv
spec:
  storageClassName: microk8s-hostpath
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    # wherever you want ffmpeg’s frames to live on the host:
    path: /mnt/data/zweiterra/jellyfin-transcode

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-transcode
  namespace: jellyfin
spec:
  storageClassName: microk8s-hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
