apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ssd-hostpath-siyuan
provisioner: microk8s.io/hostpath
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: false
