apiVersion: v1
data:
  api-token: OEJaaDFyaUY4YndPczl4TzRrWE5SallhUTFRTEhYekgwcnhrNkN6Qw==
kind: Secret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token-secret
  namespace: cert-manager
